version: '3'
services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
